---
- name: create ceilometer service user
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: service 
    user: ceilometer 
    password: "{{ ceilometer_identity_password }}"

- name: add ceilometer service user to the service tenant with the admin role
  keystone_user: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    tenant: service 
    user: ceilometer 
    role: admin

- name: add ceilometer endpoint to keystone
  keystone_service: 
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}" 
    region: "{{ openstack_region }}"
    name: ceilometer
    type: metering
    description: "Ceilometer Telemetry Service"
    public_url: "{{ ceilometer_public_url }}"
    internal_url: "{{ ceilometer_internal_url }}"
    admin_url: "{{ ceilometer_admin_url }}"

