component: neutron

neutron_api_packages:
  - "{{ component }}-server"
######################
  - openvswitch-common
  - openvswitch-switch
  - "{{ component }}-plugin-openvswitch"
  - "{{ component }}-plugin-openvswitch-agent"

neutron_api_services:
  - "{{ component }}-server"
neutron_api_config_files:
  - "{{ component }}.conf"
  - api-paste.ini


neutron_network_packages:
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
neutron_network_services:
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
neutron_network_config_files:
  - "{{ component }}.conf"
  - api-paste.ini
  - dhcp_agent.ini
  - l3_agent.ini
  - metadata_agent.ini

neutron_openvswitch_packages:
  - openvswitch-common
  - openvswitch-switch
  - "{{ component }}-plugin-openvswitch"
  - "{{ component }}-plugin-openvswitch-agent"
  # - openvswitch-datapath-dkms
neutron_openvswitch_services:
  - "{{ component }}-plugin-openvswitch-agent"
  - openvswitch-switch
neutron_openvswitch_config_files:
  - "{{ component }}.conf"
  - api-paste.ini

